<a href="https://colab.research.google.com/github/MariaAkterKhadiza/Phitron_AI-ML_Batch_01/blob/main/Module_14(ML).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}
df = pd.DataFrame(data)
print(df)

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [ ]:
df.loc[df['City'].str.contains("New")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [ ]:
df.loc[df['City'].str.contains("new",case=False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [ ]:
#start with Los
df.loc[df['City'].str.contains(r"^Los")]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [ ]:
#End with Los
df.loc[df['City'].str.contains(r"Los")]

    Name         City Department  Salary
1    Bob  Los Angeles         IT   60000
8  Sakib    H Los Ang         HR   70000

In [ ]:
df.loc[df['City'].str.contains(r"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [ ]:
df.loc[df['Name'].str.contains(r"^[AEIOU]")] #aeiou

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [ ]:
df.loc[df['City'].str.contains(r"New|Los")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000
8    Sakib    H Los Ang         HR   70000

14.2

In [ ]:
import pandas as pd

df = pd.read_csv("student_data.csv")
df

,studentId,FullName,Data structure Marks,Algorithm Marks,Python Marks,CompletionStutus,EnrolledData,Instruction,Locations
0,STU001,Student 1,90,59,82,In Progress,2025-01-01,Hybrid,Dhaka
1,STU002,Student 2,81,68,82,In Progress,2025-01-16,Hybrid,Khulna
2,STU003,Student 3,80,79,74,In Progress,2025-01-31,Hybrid,Khulna
3,STU004,Student 4,64,62,91,In Progress,2025-02-15,Offline,Khulna
4,STU005,Student 5,55,73,71,Completed,2025-03-02,Offline,Sylhet
5,STU006,Student 6,59,47,69,In Progress,2025-03-17,Hybrid,Chittagong
6,STU007,Student 7,91,79,72,In Progress,2025-04-01,Hybrid,Dhaka
7,STU008,Student 8,80,90,65,Not Started,2025-04-16,Hybrid,Dhaka
8,STU009,Student 9,65,53,95,Not Started,2025-05-01,Online,Sylhet
9,STU010,Student 10,68,92,89,Completed,2025-05-16,Online,Dhaka
10,STU011,Student 11,50,54,64,Not Started,2025-05-31,Offline,Chittagong
11,STU012,Student 12,90,56,69,Not Started,2025-06-15,Offline,Chittagong
12,STU013,Student 13,79,59,91,Not Started,2025-06-30,Online,Dhaka
13,STU014,Student 14,88,65,89,Not Started,2025-07-15,Hybrid,Sylhet
14,STU015,Student 15,51,94,89,Not Started,2025-07-30,Offline,Sylhet
15,STU016,Student 16,72,62,72,Not Started,2025-08-14,Online,Chittagong
16,STU017,Student 17,69,83,91,Not Started,2025-08-29,Offline,Dhaka
17,STU018,Student 18,84,99,99,In Progress,2025-09-13,Offline,Chittagong
18,STU019,Student 19,58,50,73,In Progress,2025-09-28,Online,Chittagong
19,STU020,Student 20,61,70,80,Not Started,2025-10-13,Online,Dhaka

In [ ]:
#adding column WITH constant value
df['Country'] = 'Bangladesh'
df

,studentId,FullName,Data structure Marks,Algorithm Marks,Python Marks,CompletionStutus,EnrolledData,Instruction,Locations,Country
0,STU001,Student 1,90,59,82,In Progress,2025-01-01,Hybrid,Dhaka,Bangladesh
1,STU002,Student 2,81,68,82,In Progress,2025-01-16,Hybrid,Khulna,Bangladesh
2,STU003,Student 3,80,79,74,In Progress,2025-01-31,Hybrid,Khulna,Bangladesh
3,STU004,Student 4,64,62,91,In Progress,2025-02-15,Offline,Khulna,Bangladesh
4,STU005,Student 5,55,73,71,Completed,2025-03-02,Offline,Sylhet,Bangladesh
5,STU006,Student 6,59,47,69,In Progress,2025-03-17,Hybrid,Chittagong,Bangladesh
6,STU007,Student 7,91,79,72,In Progress,2025-04-01,Hybrid,Dhaka,Bangladesh
7,STU008,Student 8,80,90,65,Not Started,2025-04-16,Hybrid,Dhaka,Bangladesh
8,STU009,Student 9,65,53,95,Not Started,2025-05-01,Online,Sylhet,Bangladesh
9,STU010,Student 10,68,92,89,Completed,2025-05-16,Online,Dhaka,Bangladesh
10,STU011,Student 11,50,54,64,Not Started,2025-05-31,Offline,Chittagong,Bangladesh
11,STU012,Student 12,90,56,69,Not Started,2025-06-15,Offline,Chittagong,Bangladesh
12,STU013,Student 13,79,59,91,Not Started,2025-06-30,Online,Dhaka,Bangladesh
13,STU014,Student 14,88,65,89,Not Started,2025-07-15,Hybrid,Sylhet,Bangladesh
14,STU015,Student 15,51,94,89,Not Started,2025-07-30,Offline,Sylhet,Bangladesh
15,STU016,Student 16,72,62,72,Not Started,2025-08-14,Online,Chittagong,Bangladesh
16,STU017,Student 17,69,83,91,Not Started,2025-08-29,Offline,Dhaka,Bangladesh
17,STU018,Student 18,84,99,99,In Progress,2025-09-13,Offline,Chittagong,Bangladesh
18,STU019,Student 19,58,50,73,In Progress,2025-09-28,Online,Chittagong,Bangladesh
19,STU020,Student 20,61,70,80,Not Started,2025-10-13,Online,Dhaka,Bangladesh

In [ ]:
#total marks

# তিনটি সাবজেক্টের মার্কস যোগ করে Total Marks কলাম তৈরি
df['Total Marks'] = df['Data structure Marks'] + df['Python Marks'] + df['Algorithm Marks']

df

,studentId,FullName,Data structure Marks,Algorithm Marks,Python Marks,CompletionStutus,EnrolledData,Instruction,Locations,Country,Total Marks
0,STU001,Student 1,90,59,82,In Progress,2025-01-01,Hybrid,Dhaka,Bangladesh,231
1,STU002,Student 2,81,68,82,In Progress,2025-01-16,Hybrid,Khulna,Bangladesh,231
2,STU003,Student 3,80,79,74,In Progress,2025-01-31,Hybrid,Khulna,Bangladesh,233
3,STU004,Student 4,64,62,91,In Progress,2025-02-15,Offline,Khulna,Bangladesh,217
4,STU005,Student 5,55,73,71,Completed,2025-03-02,Offline,Sylhet,Bangladesh,199
5,STU006,Student 6,59,47,69,In Progress,2025-03-17,Hybrid,Chittagong,Bangladesh,175
6,STU007,Student 7,91,79,72,In Progress,2025-04-01,Hybrid,Dhaka,Bangladesh,242
7,STU008,Student 8,80,90,65,Not Started,2025-04-16,Hybrid,Dhaka,Bangladesh,235
8,STU009,Student 9,65,53,95,Not Started,2025-05-01,Online,Sylhet,Bangladesh,213
9,STU010,Student 10,68,92,89,Completed,2025-05-16,Online,Dhaka,Bangladesh,249
10,STU011,Student 11,50,54,64,Not Started,2025-05-31,Offline,Chittagong,Bangladesh,168
11,STU012,Student 12,90,56,69,Not Started,2025-06-15,Offline,Chittagong,Bangladesh,215
12,STU013,Student 13,79,59,91,Not Started,2025-06-30,Online,Dhaka,Bangladesh,229
13,STU014,Student 14,88,65,89,Not Started,2025-07-15,Hybrid,Sylhet,Bangladesh,242
14,STU015,Student 15,51,94,89,Not Started,2025-07-30,Offline,Sylhet,Bangladesh,234
15,STU016,Student 16,72,62,72,Not Started,2025-08-14,Online,Chittagong,Bangladesh,206
16,STU017,Student 17,69,83,91,Not Started,2025-08-29,Offline,Dhaka,Bangladesh,243
17,STU018,Student 18,84,99,99,In Progress,2025-09-13,Offline,Chittagong,Bangladesh,282
18,STU019,Student 19,58,50,73,In Progress,2025-09-28,Online,Chittagong,Bangladesh,181
19,STU020,Student 20,61,70,80,Not Started,2025-10-13,Online,Dhaka,Bangladesh,211

In [ ]:
df['First Name'] = df['FullName'].str.split(' ').str[0]
df

,studentId,FullName,Data structure Marks,Algorithm Marks,Python Marks,CompletionStutus,EnrolledData,Instruction,Locations,Country,Total Marks,First Name
0,STU001,Student 1,90,59,82,In Progress,2025-01-01,Hybrid,Dhaka,Bangladesh,231,Student
1,STU002,Student 2,81,68,82,In Progress,2025-01-16,Hybrid,Khulna,Bangladesh,231,Student
2,STU003,Student 3,80,79,74,In Progress,2025-01-31,Hybrid,Khulna,Bangladesh,233,Student
3,STU004,Student 4,64,62,91,In Progress,2025-02-15,Offline,Khulna,Bangladesh,217,Student
4,STU005,Student 5,55,73,71,Completed,2025-03-02,Offline,Sylhet,Bangladesh,199,Student
5,STU006,Student 6,59,47,69,In Progress,2025-03-17,Hybrid,Chittagong,Bangladesh,175,Student
6,STU007,Student 7,91,79,72,In Progress,2025-04-01,Hybrid,Dhaka,Bangladesh,242,Student
7,STU008,Student 8,80,90,65,Not Started,2025-04-16,Hybrid,Dhaka,Bangladesh,235,Student
8,STU009,Student 9,65,53,95,Not Started,2025-05-01,Online,Sylhet,Bangladesh,213,Student
9,STU010,Student 10,68,92,89,Completed,2025-05-16,Online,Dhaka,Bangladesh,249,Student
10,STU011,Student 11,50,54,64,Not Started,2025-05-31,Offline,Chittagong,Bangladesh,168,Student
11,STU012,Student 12,90,56,69,Not Started,2025-06-15,Offline,Chittagong,Bangladesh,215,Student
12,STU013,Student 13,79,59,91,Not Started,2025-06-30,Online,Dhaka,Bangladesh,229,Student
13,STU014,Student 14,88,65,89,Not Started,2025-07-15,Hybrid,Sylhet,Bangladesh,242,Student
14,STU015,Student 15,51,94,89,Not Started,2025-07-30,Offline,Sylhet,Bangladesh,234,Student
15,STU016,Student 16,72,62,72,Not Started,2025-08-14,Online,Chittagong,Bangladesh,206,Student
16,STU017,Student 17,69,83,91,Not Started,2025-08-29,Offline,Dhaka,Bangladesh,243,Student
17,STU018,Student 18,84,99,99,In Progress,2025-09-13,Offline,Chittagong,Bangladesh,282,Student
18,STU019,Student 19,58,50,73,In Progress,2025-09-28,Online,Chittagong,Bangladesh,181,Student
19,STU020,Student 20,61,70,80,Not Started,2025-10-13,Online,Dhaka,Bangladesh,211,Student

In [ ]:
import numpy as np

df['A+ in DS'] = np.where(df['Data structure Marks']>90, 'A+' , 'A')

df

,studentId,FullName,Data structure Marks,Algorithm Marks,Python Marks,CompletionStutus,EnrolledData,Instruction,Locations,Country,Total Marks,First Name,A+ in DS
0,STU001,Student 1,90,59,82,In Progress,2025-01-01,Hybrid,Dhaka,Bangladesh,231,Student,A
1,STU002,Student 2,81,68,82,In Progress,2025-01-16,Hybrid,Khulna,Bangladesh,231,Student,A
2,STU003,Student 3,80,79,74,In Progress,2025-01-31,Hybrid,Khulna,Bangladesh,233,Student,A
3,STU004,Student 4,64,62,91,In Progress,2025-02-15,Offline,Khulna,Bangladesh,217,Student,A
4,STU005,Student 5,55,73,71,Completed,2025-03-02,Offline,Sylhet,Bangladesh,199,Student,A
5,STU006,Student 6,59,47,69,In Progress,2025-03-17,Hybrid,Chittagong,Bangladesh,175,Student,A
6,STU007,Student 7,91,79,72,In Progress,2025-04-01,Hybrid,Dhaka,Bangladesh,242,Student,A+
7,STU008,Student 8,80,90,65,Not Started,2025-04-16,Hybrid,Dhaka,Bangladesh,235,Student,A
8,STU009,Student 9,65,53,95,Not Started,2025-05-01,Online,Sylhet,Bangladesh,213,Student,A
9,STU010,Student 10,68,92,89,Completed,2025-05-16,Online,Dhaka,Bangladesh,249,Student,A
10,STU011,Student 11,50,54,64,Not Started,2025-05-31,Offline,Chittagong,Bangladesh,168,Student,A
11,STU012,Student 12,90,56,69,Not Started,2025-06-15,Offline,Chittagong,Bangladesh,215,Student,A
12,STU013,Student 13,79,59,91,Not Started,2025-06-30,Online,Dhaka,Bangladesh,229,Student,A
13,STU014,Student 14,88,65,89,Not Started,2025-07-15,Hybrid,Sylhet,Bangladesh,242,Student,A
14,STU015,Student 15,51,94,89,Not Started,2025-07-30,Offline,Sylhet,Bangladesh,234,Student,A
15,STU016,Student 16,72,62,72,Not Started,2025-08-14,Online,Chittagong,Bangladesh,206,Student,A
16,STU017,Student 17,69,83,91,Not Started,2025-08-29,Offline,Dhaka,Bangladesh,243,Student,A
17,STU018,Student 18,84,99,99,In Progress,2025-09-13,Offline,Chittagong,Bangladesh,282,Student,A
18,STU019,Student 19,58,50,73,In Progress,2025-09-28,Online,Chittagong,Bangladesh,181,Student,A
19,STU020,Student 20,61,70,80,Not Started,2025-10-13,Online,Dhaka,Bangladesh,211,Student,A

In [ ]:
df

,studentId,FullName,Data structure Marks,Algorithm Marks,Python Marks,CompletionStutus,EnrolledData,Instruction,Locations,Country,Total Marks,First Name,A+ in DS
0,STU001,Student 1,90,59,82,In Progress,2025-01-01,Hybrid,Dhaka,Bangladesh,231,Student,A
1,STU002,Student 2,81,68,82,In Progress,2025-01-16,Hybrid,Khulna,Bangladesh,231,Student,A
2,STU003,Student 3,80,79,74,In Progress,2025-01-31,Hybrid,Khulna,Bangladesh,233,Student,A
3,STU004,Student 4,64,62,91,In Progress,2025-02-15,Offline,Khulna,Bangladesh,217,Student,A
4,STU005,Student 5,55,73,71,Completed,2025-03-02,Offline,Sylhet,Bangladesh,199,Student,A
5,STU006,Student 6,59,47,69,In Progress,2025-03-17,Hybrid,Chittagong,Bangladesh,175,Student,A
6,STU007,Student 7,91,79,72,In Progress,2025-04-01,Hybrid,Dhaka,Bangladesh,242,Student,A+
7,STU008,Student 8,80,90,65,Not Started,2025-04-16,Hybrid,Dhaka,Bangladesh,235,Student,A
8,STU009,Student 9,65,53,95,Not Started,2025-05-01,Online,Sylhet,Bangladesh,213,Student,A
9,STU010,Student 10,68,92,89,Completed,2025-05-16,Online,Dhaka,Bangladesh,249,Student,A
10,STU011,Student 11,50,54,64,Not Started,2025-05-31,Offline,Chittagong,Bangladesh,168,Student,A
11,STU012,Student 12,90,56,69,Not Started,2025-06-15,Offline,Chittagong,Bangladesh,215,Student,A
12,STU013,Student 13,79,59,91,Not Started,2025-06-30,Online,Dhaka,Bangladesh,229,Student,A
13,STU014,Student 14,88,65,89,Not Started,2025-07-15,Hybrid,Sylhet,Bangladesh,242,Student,A
14,STU015,Student 15,51,94,89,Not Started,2025-07-30,Offline,Sylhet,Bangladesh,234,Student,A
15,STU016,Student 16,72,62,72,Not Started,2025-08-14,Online,Chittagong,Bangladesh,206,Student,A
16,STU017,Student 17,69,83,91,Not Started,2025-08-29,Offline,Dhaka,Bangladesh,243,Student,A
17,STU018,Student 18,84,99,99,In Progress,2025-09-13,Offline,Chittagong,Bangladesh,282,Student,A
18,STU019,Student 19,58,50,73,In Progress,2025-09-28,Online,Chittagong,Bangladesh,181,Student,A
19,STU020,Student 20,61,70,80,Not Started,2025-10-13,Online,Dhaka,Bangladesh,211,Student,A

In [ ]:
df1 = pd.read_csv('student_data.csv')
df1

,studentId,FullName,Data structure Marks,Algorithm Marks,Python Marks,CompletionStutus,EnrolledData,Instruction,Locations
0,STU001,Student 1,90,59,82,In Progress,2025-01-01,Hybrid,Dhaka
1,STU002,Student 2,81,68,82,In Progress,2025-01-16,Hybrid,Khulna
2,STU003,Student 3,80,79,74,In Progress,2025-01-31,Hybrid,Khulna
3,STU004,Student 4,64,62,91,In Progress,2025-02-15,Offline,Khulna
4,STU005,Student 5,55,73,71,Completed,2025-03-02,Offline,Sylhet
5,STU006,Student 6,59,47,69,In Progress,2025-03-17,Hybrid,Chittagong
6,STU007,Student 7,91,79,72,In Progress,2025-04-01,Hybrid,Dhaka
7,STU008,Student 8,80,90,65,Not Started,2025-04-16,Hybrid,Dhaka
8,STU009,Student 9,65,53,95,Not Started,2025-05-01,Online,Sylhet
9,STU010,Student 10,68,92,89,Completed,2025-05-16,Online,Dhaka
10,STU011,Student 11,50,54,64,Not Started,2025-05-31,Offline,Chittagong
11,STU012,Student 12,90,56,69,Not Started,2025-06-15,Offline,Chittagong
12,STU013,Student 13,79,59,91,Not Started,2025-06-30,Online,Dhaka
13,STU014,Student 14,88,65,89,Not Started,2025-07-15,Hybrid,Sylhet
14,STU015,Student 15,51,94,89,Not Started,2025-07-30,Offline,Sylhet
15,STU016,Student 16,72,62,72,Not Started,2025-08-14,Online,Chittagong
16,STU017,Student 17,69,83,91,Not Started,2025-08-29,Offline,Dhaka
17,STU018,Student 18,84,99,99,In Progress,2025-09-13,Offline,Chittagong
18,STU019,Student 19,58,50,73,In Progress,2025-09-28,Online,Chittagong
19,STU020,Student 20,61,70,80,Not Started,2025-10-13,Online,Dhaka

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 85, 95, 90]
}

df = pd.DataFrame(data)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     85
4    David     Tokyo     95
5      Bob    London     90

In [ ]:
df['Name'].unique()#unique works on only series

array(['Alice', 'Bob', 'Charlie', 'David'], dtype=object)

In [ ]:
df1 = pd.read_csv('student_data.csv')
df1

,studentId,FullName,Data structure Marks,Algorithm Marks,Python Marks,CompletionStutus,EnrolledData,Instruction,Locations
0,STU001,Student 1,90,59,82,In Progress,2025-01-01,Hybrid,Dhaka
1,STU002,Student 2,81,68,82,In Progress,2025-01-16,Hybrid,Khulna
2,STU003,Student 3,80,79,74,In Progress,2025-01-31,Hybrid,Khulna
3,STU004,Student 4,64,62,91,In Progress,2025-02-15,Offline,Khulna
4,STU005,Student 5,55,73,71,Completed,2025-03-02,Offline,Sylhet
5,STU006,Student 6,59,47,69,In Progress,2025-03-17,Hybrid,Chittagong
6,STU007,Student 7,91,79,72,In Progress,2025-04-01,Hybrid,Dhaka
7,STU008,Student 8,80,90,65,Not Started,2025-04-16,Hybrid,Dhaka
8,STU009,Student 9,65,53,95,Not Started,2025-05-01,Online,Sylhet
9,STU010,Student 10,68,92,89,Completed,2025-05-16,Online,Dhaka
10,STU011,Student 11,50,54,64,Not Started,2025-05-31,Offline,Chittagong
11,STU012,Student 12,90,56,69,Not Started,2025-06-15,Offline,Chittagong
12,STU013,Student 13,79,59,91,Not Started,2025-06-30,Online,Dhaka
13,STU014,Student 14,88,65,89,Not Started,2025-07-15,Hybrid,Sylhet
14,STU015,Student 15,51,94,89,Not Started,2025-07-30,Offline,Sylhet
15,STU016,Student 16,72,62,72,Not Started,2025-08-14,Online,Chittagong
16,STU017,Student 17,69,83,91,Not Started,2025-08-29,Offline,Dhaka
17,STU018,Student 18,84,99,99,In Progress,2025-09-13,Offline,Chittagong
18,STU019,Student 19,58,50,73,In Progress,2025-09-28,Online,Chittagong
19,STU020,Student 20,61,70,80,Not Started,2025-10-13,Online,Dhaka

In [ ]:
len(df1['Data structure Marks'].unique())  # ✅ Correct: use () to call the function

18

In [ ]:
df1['Data structure Marks'].nunique()  # ✅ Correct: directly counts unique values

18

In [ ]:
df.nunique()

Name     4
City     4
Score    4
dtype: int64

In [ ]:
df1['Data structure Marks'].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: Data structure Marks, dtype: bool

In [ ]:
df1['Data structure Marks'].notnull()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
Name: Data structure Marks, dtype: bool

# Handling Duplicates Value

In [2]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 70, 95, 90]
}

df = pd.DataFrame(data)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95
5      Bob    London     90

In [3]:
df.duplicated().sum()

np.int64(1)

In [4]:
df.drop_duplicates()

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [8]:
df.drop_duplicates(inplace = True)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [9]:
#name er basic  duplicate deletion
df.drop_duplicates(subset=['Name'])

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [10]:
#city
df.drop_duplicates(subset=['City'])

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [11]:
df.drop_duplicates(subset=['Name'],keep='last')

      Name      City  Score
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [12]:
df.drop_duplicates(subset=['Name'],keep='first')

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

Handling Null  **Values**

In [17]:
df = pd.read_csv('student_data.csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [20]:
df.dropna(how='all',inplace = True)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [21]:
df.dropna(subset=['Python Marks'])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [23]:
df.dropna(subset=['Python Marks','Algorithm Marks'])
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [24]:
df.fillna(0)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [25]:
df = pd.read_csv('student_data.csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df['FullName'].fillna('unknown')

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
20             unknown
Name: FullName, dtype: object

In [28]:
df['Python Marks'].fillna(df['Python Marks'].mean(),inplace=True)
df

/tmp/ipython-input-60110564.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Python Marks'].fillna(df['Python Marks'].mean(),inplace=True)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN

# Statistical Functions in pandas

In [31]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN

In [32]:
df.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka

In [35]:

df['Data Structure Marks'].sum()

np.float64(1344.0)

In [34]:
# sum
df['Data Structure Marks'].sum()

np.float64(1344.0)

In [36]:
# max and min
print(df['Data Structure Marks'].min())
df['Data Structure Marks'].max()

72.0

94.0

In [37]:
#mean -> average

df['Data Structure Marks'].mean()

np.float64(84.0)

In [38]:
#median
df['Data Structure Marks'].median()

85.5

In [39]:
#mode_higghest frequency er number
df['Data Structure Marks'].mode()

0    75.0
1    85.0
2    86.0
3    88.0
Name: Data Structure Marks, dtype: float64

In [40]:
#standard deviation ->std
df['Data Structure Marks'].std()

6.501281924871945

In [41]:
#correlation matrix
df[['Data Structure Marks','Python Marks']].corr()

                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.776845
Python Marks                      0.776845      1.000000

In [42]:
#sum in different columns row wise
df[['Data Structure Marks','Python Marks']].sum(axis=1)

0     173.000000
1     177.666667
2     173.000000
3     160.000000
4      95.000000
5     153.000000
6     165.666667
7     166.000000
8     148.000000
9     177.000000
10     91.000000
11    172.000000
12    154.000000
13     85.666667
14    170.000000
15    179.666667
16    183.000000
17    173.000000
18     85.666667
19    175.000000
20     85.666667
dtype: float64

In [43]:
df['Total Marks'] = df.iloc[::,2:5].sum(axis=1)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667

In [45]:
df.describe()
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667

# apply function on **df**

In [49]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000,0.916667
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667,0.978723
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000,0.932624
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000,0.810284
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,0.049645
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000,0.757092
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667,0.851064
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000,0.858156
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000,0.714539
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000,0.959220
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,0.028369
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000,0.911348
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000,0.762411
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,0.000000
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000,0.906028
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667,1.000000
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000,0.996454
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000,0.932624
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,0.000000
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000,0.932624
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667,0.000000

In [51]:
#min max scaling

mn = df['Total Marks'].min()
mx = df['Total Marks'].max()


df['Scaled Marks'] = df['Total Marks'].apply(lambda x : (x-mn)/(mx-mn))
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000,0.916667
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667,0.978723
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000,0.932624
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000,0.810284
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,0.049645
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000,0.757092
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667,0.851064
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000,0.858156
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000,0.714539
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000,0.959220
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,0.028369
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000,0.911348
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000,0.762411
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,0.000000
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000,0.906028
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667,1.000000
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000,0.996454
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000,0.932624
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,0.000000
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000,0.932624
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667,0.000000

In [54]:
# custom built function

def grading_system(marks):

    if marks >=260:
        return 'A+'
    elif marks>=250:
        return 'A'
    else:
        return 'A-'


df['Grade'] = df['Total Marks'].apply(grading_system)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks,Grade
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000,0.916667,A
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667,0.978723,A+
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000,0.932624,A+
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000,0.810284,A-
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,0.049645,A-
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000,0.757092,A-
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667,0.851064,A-
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000,0.858156,A-
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000,0.714539,A-
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000,0.959220,A+
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,0.028369,A-
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000,0.911348,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000,0.762411,A-
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,0.000000,A-
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000,0.906028,A
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667,1.000000,A+
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000,0.996454,A+
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000,0.932624,A+
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,0.000000,A-
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000,0.932624,A+
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667,0.000000,A-

In [57]:
def marking_system(df):
    a = df['Data Structure Marks'] * 2
    b = df['Python Marks'] * 3
    c = df['Algorithm Marks'] * 4

    return a+b+c



df['Exceptional Marks'] = df.apply(marking_system,axis=1)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000,0.916667,A,774.0
1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,269.666667,0.978723,A+,809.0
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000,0.932624,A+,783.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000,0.810284,A-,714.0
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,0.049645,A-,NaN
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000,0.757092,A-,684.0
6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,245.666667,0.851064,A-,737.0
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000,0.858156,A-,741.0
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000,0.714539,A-,660.0
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000,0.959220,A+,798.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,0.028369,A-,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000,0.911348,A,771.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000,0.762411,A-,687.0
13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.666667,0.000000,A-,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000,0.906028,A,768.0
15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,273.666667,1.000000,A+,821.0
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,273.000000,0.996454,A+,819.0
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,261.000000,0.932624,A+,783.0
18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,85.666667,0.000000,A-,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,261.000000,0.932624,A+,783.0
20,NaN,NaN,NaN,NaN,85.666667,NaN,NaN,NaN,NaN,85.666667,0.000000,A-,NaN

# datetime and time delta

In [71]:
df = pd.read_csv('student_completed_data.csv')
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [72]:
df['EnrollmentDate']

0     2024-09-01
1     2024-08-11
2     2024-05-08
3     2024-07-05
4     2024-02-01
5     2024-09-07
6     2024-06-07
7     2024-03-22
8     2024-02-12
9     2024-06-19
10    2024-03-14
11    2024-08-04
12    2024-06-07
13    2024-01-04
14    2024-02-22
15    2024-03-23
16    2024-01-18
17    2024-06-23
18    2024-04-19
19    2024-07-21
Name: EnrollmentDate, dtype: object

In [73]:
df['EntrollmentDate'] = pd.to_datetime(df['EnrollmentDate'])

df['EnrollmentDate']

0     2024-09-01
1     2024-08-11
2     2024-05-08
3     2024-07-05
4     2024-02-01
5     2024-09-07
6     2024-06-07
7     2024-03-22
8     2024-02-12
9     2024-06-19
10    2024-03-14
11    2024-08-04
12    2024-06-07
13    2024-01-04
14    2024-02-22
15    2024-03-23
16    2024-01-18
17    2024-06-23
18    2024-04-19
19    2024-07-21
Name: EnrollmentDate, dtype: object

In [74]:
df['Enrollment Year'] = df['EntrollmentDate'].dt.year
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,EntrollmentDate,Enrollment Year
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024-09-01,2024
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024-08-11,2024
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024-05-08,2024
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024-07-05,2024
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024-02-01,2024
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024-09-07,2024
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024-06-07,2024
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024-03-22,2024
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024-02-12,2024
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024-06-19,2024
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024-03-14,2024
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024-08-04,2024
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024-06-07,2024
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024-01-04,2024
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024-02-22,2024
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024-03-23,2024
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024-01-18,2024
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024-06-23,2024
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024-04-19,2024
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024-07-21,2024

In [81]:
import pandas as pd
df = pd.read_csv('student_completed_data.csv')
# Convert to datetime
df['EnrollmentDate'] = pd.to_datetime(df['EnrollmentDate'], errors='coerce')

# Now you can use .dt safely
df['Enrollment Year'] = df['EnrollmentDate'].dt.year
df['Enrollment Day'] = df['EnrollmentDate'].dt.day

In [82]:
df['Enrollment Year'] = df['EnrollmentDate'].dt.year
df['Enrollment Date'] = df['EnrollmentDate'].dt.day
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Day,Enrollment Date
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,1,1
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,11,11
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,8,8
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,5,5
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,1,1
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,7,7
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,7,7
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,22,22
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,12,12
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,19,19
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,14,14
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,4,4
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,7,7
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,4,4
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,22,22
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,23,23
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,18,18
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,23,23
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,19,19
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,21,21

In [84]:
df['FinishedDate'] = pd.to_datetime(df['FinishedDate'])
df['Total time taken to finish']= df['FinishedDate'] - df['EnrollmentDate']
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Day,Enrollment Date,Total time taken to finish
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,1,1,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,11,11,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,8,8,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,5,5,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,1,1,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,7,7,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,7,7,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,22,22,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,12,12,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,19,19,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,14,14,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,4,4,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,7,7,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,4,4,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,22,22,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,23,23,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,18,18,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,23,23,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,19,19,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,21,21,82 days

# GroupBy in DF

In [86]:
df.groupby('Instructor')

In [90]:
group = df.groupby('Instructor')
df.drop(columns=['StudentID','FullName','CompletionStatus'],inplace=True)
group = df.groupby('Instructor')
group.sum()

KeyError: "['StudentID', 'FullName', 'CompletionStatus'] not found in axis"

In [91]:
group.min()

,EnrollmentDate,FinishedDate,Location,Total Marks,Enrollment Year,Enrollment Day,Enrollment Date,Total time taken to finish
Instructor,,,,,,,,
Mr. David,2024-01-04,2024-03-16,Chattogram,236,2024,1,1,43 days
Mr. Karim,2024-02-12,2024-06-08,Dhaka,253,2024,4,4,80 days
Ms. Salma,2024-03-22,2024-05-01,Dhaka,234,2024,1,1,40 days

In [92]:
group.max()

,EnrollmentDate,FinishedDate,Location,Total Marks,Enrollment Year,Enrollment Day,Enrollment Date,Total time taken to finish
Instructor,,,,,,,,
Mr. David,2024-09-07,2024-12-31,Sylhet,291,2024,23,23,115 days
Mr. Karim,2024-08-11,2024-11-07,Sylhet,291,2024,21,21,120 days
Ms. Salma,2024-09-01,2024-12-23,Rajshahi,300,2024,23,23,113 days

In [93]:
group.first()

,EnrollmentDate,FinishedDate,Location,Total Marks,Enrollment Year,Enrollment Day,Enrollment Date,Total time taken to finish
Instructor,,,,,,,,
Mr. David,2024-02-01,2024-04-17,Sylhet,254,2024,1,1,76 days
Mr. Karim,2024-08-11,2024-11-07,Dhaka,271,2024,11,11,88 days
Ms. Salma,2024-09-01,2024-12-23,Khulna,300,2024,1,1,113 days

In [94]:
group.last()

,EnrollmentDate,FinishedDate,Location,Total Marks,Enrollment Year,Enrollment Day,Enrollment Date,Total time taken to finish
Instructor,,,,,,,,
Mr. David,2024-06-23,2024-09-20,Dhaka,278,2024,23,23,89 days
Mr. Karim,2024-07-21,2024-10-11,Khulna,253,2024,21,21,82 days
Ms. Salma,2024-03-23,2024-06-21,Rajshahi,234,2024,23,23,90 days

In [95]:
df

,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Day,Enrollment Date,Total time taken to finish
0,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,1,1,113 days
1,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,11,11,88 days
2,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,8,8,92 days
3,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,5,5,80 days
4,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,1,1,76 days
5,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,7,7,115 days
6,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,7,7,43 days
7,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,22,22,40 days
8,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,12,12,117 days
9,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,19,19,61 days
10,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,14,14,89 days
11,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,4,4,82 days
12,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,7,7,57 days
13,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,4,4,79 days
14,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,22,22,84 days
15,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,23,23,90 days
16,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,18,18,58 days
17,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,23,23,89 days
18,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,19,19,120 days
19,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,21,21,82 days

In [96]:
df.sort_values('Total Marks', ascending=False).groupby('Instructor').head(5)

,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Day,Enrollment Date,Total time taken to finish
0,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,1,1,113 days
8,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,12,12,117 days
14,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,22,22,84 days
9,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,19,19,61 days
13,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,4,4,79 days
10,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,14,14,89 days
17,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,23,23,89 days
18,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,19,19,120 days
5,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,7,7,115 days
1,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,11,11,88 days
3,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,5,5,80 days
2,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,8,8,92 days
7,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,22,22,40 days
15,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,23,23,90 days

In [97]:
import pandas as pd

df = pd.read_csv('student_completed_data.csv')
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [98]:

df['Total Marks']>250

0      True
1      True
2      True
3      True
4      True
5      True
6     False
7     False
8      True
9      True
10     True
11     True
12    False
13     True
14     True
15    False
16    False
17     True
18     True
19     True
Name: Total Marks, dtype: bool

In [99]:

(df['Total Marks']>250).sum()

np.int64(15)

In [101]:
#Problem_01()

import pandas as pd
def delete_duplicate_emails(person:pd.DataFrame)->None:
  person.sort_values('id',inplace=True)
  person.drop_duplicates(sebset = ['email'],inplace=True)

# quiz

In [105]:
import pandas as pd

data = {
    "Name":["Alice","Bob","Chrlie"],
    "Age" : [25,30,35],
    "City" : ["New York","London","Paris"]
}
df = pd.DataFrame(data)
df(shape)

NameError: name 'shape' is not defined